package by.pvt.dto;

import java.util.Date;

public class Clients {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.client_id
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.first_name
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.second_name
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    private String secondName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.date_of_birth
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.male_female
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    private String maleFemale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.e-mail
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    private String eMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.client_id
     *
     * @return the value of clients.client_id
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.client_id
     *
     * @param clientId the value for clients.client_id
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.first_name
     *
     * @return the value of clients.first_name
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.first_name
     *
     * @param firstName the value for clients.first_name
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.second_name
     *
     * @return the value of clients.second_name
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public String getSecondName() {
        return secondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.second_name
     *
     * @param secondName the value for clients.second_name
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.date_of_birth
     *
     * @return the value of clients.date_of_birth
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.date_of_birth
     *
     * @param dateOfBirth the value for clients.date_of_birth
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.male_female
     *
     * @return the value of clients.male_female
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public String getMaleFemale() {
        return maleFemale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.male_female
     *
     * @param maleFemale the value for clients.male_female
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public void setMaleFemale(String maleFemale) {
        this.maleFemale = maleFemale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.e-mail
     *
     * @return the value of clients.e-mail
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.e-mail
     *
     * @param eMail the value for clients.e-mail
     *
     * @mbg.generated Wed Jul 17 10:10:49 MSK 2019
     */
    public void seteMail(String eMail) {
        this.eMail = eMail;
    }
}